'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
type Key={id:string;name:string;prefix:string;created_at:string;last_used_at:string|null;revoked_at:string|null};
export default function ApiAccessPage(){
  const [keys,setKeys]=useState<Key[]>([]);const [enabled,setEnabled]=useState(false);const [name,setName]=useState('');const [secret,setSecret]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function load(){const r=await fetch('/api/account/api-keys');const d=await r.json();if(!r.ok)throw new Error(d.error);setKeys(d.keys);setEnabled(d.enabled);}
  useEffect(()=>{const timer=setTimeout(()=>void load().catch(e=>setMessage(e.message)),0);return()=>clearTimeout(timer);},[]);
  async function create(){setBusy(true);setMessage('');setSecret('');try{const r=await fetch('/api/account/api-keys',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSecret(d.token);setName('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to create key.');}finally{setBusy(false);}}
  async function revoke(id:string){setBusy(true);setSecret('');try{const r=await fetch(`/api/account/api-keys?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(!r.ok)throw new Error('Unable to revoke key.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to revoke key.');}finally{setBusy(false);}}
  return <main className="mx-auto w-full min-w-0 max-w-3xl space-y-6 px-4 py-8"><header className="flex justify-between gap-4"><h1 className="text-3xl font-bold">API access</h1><Link href="/" className="underline">Back to store</Link></header>
    <p className="text-sm text-zinc-600">Connect your systems to your company prices and current stock. Prices exclude VAT. Keys only read catalogue data.</p>
    <a href="/api/account/catalogue.csv" className="inline-block rounded-lg border px-4 py-2 font-semibold">Download catalogue CSV</a>
    {message&&<p role="alert" className="rounded-lg bg-amber-50 p-3">{message}</p>}
    {enabled?<form className="flex flex-wrap gap-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();void create();}}><label className="grow text-sm font-semibold">Key name<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Stock integration" className="mt-1 block w-full rounded-lg border px-3 py-2"/></label><button disabled={busy} className="self-end rounded-lg bg-zinc-950 px-4 py-2 text-white disabled:opacity-50">Generate key</button></form>:<p className="rounded-lg bg-zinc-100 p-4">An administrator needs to enable API access for your user account.</p>}
    {secret&&<section aria-label="New API key" className="space-y-3 rounded-xl border border-amber-300 bg-amber-50 p-4"><p className="font-semibold">Copy this key now. It is shown only once.</p><code className="block break-all select-all text-sm">{secret}</code><button className="rounded-lg border px-3 py-2" onClick={()=>void navigator.clipboard.writeText(secret).then(()=>setMessage('Key copied.')).catch(()=>setMessage('Select and copy the key above.'))}>Copy key</button><button className="ml-3 underline" onClick={()=>setSecret('')}>Done</button></section>}
    <section className="space-y-3"><h2 className="text-lg font-bold">Your keys</h2>{keys.map(k=><article key={k.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div><p className="font-semibold">{k.name}{k.revoked_at?' · Revoked':''}</p><p className="text-sm text-zinc-500">{k.prefix}… · Last used: {k.last_used_at?new Date(k.last_used_at).toLocaleString():'Never'}</p></div>{!k.revoked_at&&<button disabled={busy} onClick={()=>void revoke(k.id)} className="rounded-lg border px-3 py-2 text-sm">Revoke</button>}</article>)}</section>
    <section className="space-y-3 rounded-xl bg-zinc-50 p-4 text-sm"><h2 className="text-lg font-bold">Integration details</h2><p>Send your key in the <code>Authorization: Bearer YOUR_KEY</code> header.</p><pre className="overflow-x-auto rounded border bg-white p-3">GET https://store.thanda.solar/api/v1/products?limit=100</pre><p>Follow <code>next_cursor</code> as the next request’s <code>cursor</code>. Maximum 250 products per page and 60 requests per minute across your keys. Use <code>format=csv</code> for a complete CSV export.</p><p>Save the response ETag and send it in <code>If-None-Match</code> to check for changes. A 304 means unchanged. A 409 means the catalogue changed while paging; restart from the first page. For 429, wait for <code>Retry-After</code>.</p><p>Each product includes supplier, SKU, description, your company’s price excluding VAT, currency, Thanda stock, supplier stock, successor SKU and update timestamps. Null means unavailable or not yet recorded. Your integration controls updates to your own accounting system.</p></section>
  </main>;
}
